#!/usr/bin/env bash
#script that configures a new Ubuntu machine
sudo apt-get update
sudo apt-get install -y nginx

sed -i 's/listen [0-9]*;/listen 80;/' "/etc/nginx/sites-available/default"
sed -i 's/listen [::] [0-9]*;/listen [::] 80;/' "/etc/nginx/sites-available/default"
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
