#!/usr/bin/env bash
#script that configures a new Ubuntu machine
sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i 's/listen [0-9]*;/listen 80;/' "/etc/nginx/sites-available/default"
sudo sed -i 's/listen [::] [0-9]*;/listen [::] 80;/' "/etc/nginx/sites-available/default"
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/server_name _;/a\\tlocation / {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
:sudo service nginx restart
