#!/usr/bin/env bash
#script that Configure Nginx server to have a custom 404 page
sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i 's/listen [0-9]*;/listen 80;/' "/etc/nginx/sites-available/default"
sudo sed -i 's/listen [::] [0-9]*;/listen [::] 80;/' "/etc/nginx/sites-available/default"
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i 's/listen 80 default_server;/&\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/' "/etc/nginx/sites-available/default"
sudo service nginx restart
