#!/usr/bin/env bash
#script that Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i 's/listen [0-9]*;/listen 80;/' "/etc/nginx/sites-available/default"
sudo sed -i 's/listen [::] [0-9]*;/listen [::] 80;/' "/etc/nginx/sites-available/default"
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/server_name _;/a\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' "/etc/nginx/sites-available/default"
sudo sed -i 's/listen 80 default_server;/&\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/' "/etc/nginx/sites-available/default"
sudo sed -i 's/listen 80 default_server;/&\n\tadd_header X-Served-By $HOSTNAME;/' /etc/nginx/sites-available/default
sudo service nginx restart
