#!/usr/bin/env bash
#script that configures a server  
apt-get update  
apt-get install -y nginx    
rm /etc/nginx/sites-enabled/default  
cat <<EOL > /etc/nginx/sites-available/default  
server {  
    listen 80;  
    server_name _;  
    
    location / {  
        root /var/www/html;  
        index index.html index.htm;  
    }  
}  
EOL  
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/  
service nginx start
