#!/usr/bin/env bash
#script that configures a server
sudo apt-get update
sudo apt install -y nginx
sudo sed -i 's/listen [0-9]*;/listen 80;/' "/etc/nginx/sites-available/default"
sudo sed -i 's/listen [::] [0-9]*;/listen [::] 80;/' "/etc/nginx/sites-available/default"
sudo service nginx restart
