#!/usr/bin/env bash
# This script is displays The content of the current directory In a list format
for file in *; do
    # Check if the file is not hidden and is a regular file (not a directory)
    if [[ ! "$file" == .* && -f "$file" ]]; then
        # Extract the part of the name after the first dash
        filename=$(echo "$file" | cut -d'-' -f2-)
        # Display the filename
        echo "$filename"
    fi
done
