#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server
cp /etc/hosts ~/hosts.new
echo "localhost 127.0.0.2" > ~/hosts.new
echo "facebook.com 8.8.8.8" > ~/hosts.new
cp -f ~/hosts.new /etc/hosts
